version: '3'

services:

  eldavosblog-api:
    image: mscblog/user-api:latest
    ports:
      - 3001:3000
    networks:
      main:
        aliases:
          - eldavosblog-api
    command: >
      /bin/bash -c "sleep 5; node ."
networks:
  main:

volumes:
  yarn:
